new_railtutorial: "http://news.railstutorial.org"
railtoturial: "http://www.railstutorial.org"
railstutorial_book: "http://www.railstutorial.org/book"
screen_railtutorial: "http://screencasts.railstutorial.org"
rubyonrail: "http://rubyonrails.org"
contact_rail: "http://www.railstutorial.org/contact"
help_rail: "http://www.railstutorial.org/help"
michael: "http://www.michaelhartl.com"
gravatar_email: "http://gravatar.com/emails"
users:
  gravatar_size: 50
microposts:
  content_max: 140
  gravatar_size: 50
shared:
  gravatar_size: 50

