new_railtutorial: "http://news.railstutorial.org"
railtoturial: "http://www.railstutorial.org"
railstutorial_book: "http://www.railstutorial.org/book"
screen_railtutorial: "http://screencasts.railstutorial.org"
rubyonrail: "http://rubyonrails.org"
contact_rail: "http://www.railstutorial.org/contact"
help_rail: "http://www.railstutorial.org/help"
michael: "http://www.michaelhartl.com"
user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
